---
- name: checking url response on servers
  uri:
    url: "{{item}}"
    status_code: 200
  with_items:    
     - http://172.31.29.249
     - http://172.31.31.248
     - http://172.31.12.236
     - http://172.31.4.0
