---
- name: installing apache2
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
- name: installing httpd
  yum:
    name: httpd
    state: present
    update_cache: yes
  when: ansible_distribution == "RedHat"


