---
- name: configuring tomcat9
  copy:
    src: "{{src1}}"
    dest: "{{dest1}}"
- name: replacing port 8080 to 9090
  replace:
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"  
- name: restarting tomcat9
  service:
     name: "{{pkg1}}"
     state: "{{state2}}"
- name: pause for 2 mins
  pause:
     minutes: "{{min}}"  
  notify: check url response     
